---
title: "Final Project Milestone 8"
author: "Michael Wu"
date: "4/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(gt)
library(readr)
library(readxl)
library(rvest)
library(ggthemes)
library(lubridate)
```

### the Coronavirus Project.



```{r loading_data, echo=FALSE}
# Loading the untidy version of the coronavirus data forked from the Johns Hopkins' GitHub repo
# Specifying column types to avoid any forms of errors

untidy_covidata_global <- read.csv('raw-data/JH-covid19-rawdata/time_series_covid19_confirmed_global.csv') %>%
  clean_names()

untidy_covidata_us <- read.csv('raw-data/JH-covid19-rawdata/time_series_covid19_confirmed_US.csv') %>%
  clean_names()

unemployment_data_by_state <- read_xlsx("raw-data/DOL-unemployment-rawdata/weekly_unemployment_claims.xlsx") %>%
  clean_names() %>%
  mutate(date = mdy(as.character(date)))

```


```{r tidying-data, echo=FALSE}
# Tidying the untidy_covidata tibble using pivot_longer
# Pivoting so that dates will now be row data entries instead of columns as they were originally
# Removing extraneous or unecessary columns so that the tibble will be smaller, these are huge data tables

covidata_us <- untidy_covidata_us %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "date",
    names_prefix = "x",
    values_to = "cases",
    values_drop_na = TRUE
  ) %>%
  select(-uid, -iso2, -iso3, -code3, -fips, -lat, -long, -combined_key) %>%
  rename(county = admin2, country = country_region) %>%
  mutate(date = mdy(as.character(date))) 
```



### Preliminary Plots for the Coronavirus Outbreak


```{r plot-NY-covidata, fig.align='center', echo = FALSE}
# Find the most affected states in the United States
# Would use log scales like in China's case below, but the case reporting is so erratic
# that the graphs for log scales on the y-axis looks so poor.
# NEED TO: do some basic data cleanup because the graph displays all the county-wide 
# confirmed case counts instead of the totals for the state

new_york_covidata <- covidata_us %>%
  filter(province_state == "New York") %>%
  group_by(date) %>%
  summarize(total_cases = sum(cases)) %>%
  mutate(days = 1:107)

new_york_covidata$deriv_cases = c(diff(new_york_covidata$total_cases) / diff(new_york_covidata$days), NA)

new_york_unemployment <- unemployment_data_by_state %>%
  filter(province_state == "New York")

ggplot(new_york_unemployment, aes(x = date, y = initial_claims)) +
  geom_line() +
  geom_smooth(se = FALSE, span = 0.5) +
  labs(title = "Weekly Unemployment Filings in New York State",
       subtitle = "As of April 24th",
       x = "Date",
       y = "Case Count") +
  theme_classic()

ggplot(new_york_covidata, aes(x = date, y = deriv_cases)) +
  geom_line() +
  geom_smooth(se = FALSE, span = 0.3) +
  labs(title = "Growth of Covid-19 Cases in New York State",
       subtitle = "As of April 24th",
       x = "Date",
       y = "First Derivative of Case Count") +
  theme_classic()

ggplot(new_york_covidata, aes(x = date, y = total_cases)) +
  geom_line() +
  labs(title = "Total Covid-19 Cases in New York State",
       subtitle = "As of April 24th",
       x = "Date",
       y = "First Derivative of Case Count") +
  theme_classic()
  
```

```{r plot-arkansas-covidata, fig.align='center', echo = FALSE}
# Find the most affected states in the United States
# Would use log scales like in China's case below, but the case reporting is so erratic
# that the graphs for log scales on the y-axis looks so poor.
# NEED TO: do some basic data cleanup because the graph displays all the county-wide 
# confirmed case counts instead of the totals for the state

arkansas_covidata <- covidata_us %>%
  filter(province_state == "North Dakota") %>%
  group_by(date) %>%
  summarize(total_cases = sum(cases)) %>%
  mutate(days = 1:107)

arkansas_covidata$deriv_cases = c(diff(arkansas_covidata$total_cases) / diff(arkansas_covidata$days), NA)

arkansas_unemployment <- unemployment_data_by_state %>%
  filter(province_state == "North Dakota")

ggplot(arkansas_unemployment, aes(x = date, y = initial_claims)) +
  geom_line() +
  geom_smooth(se = FALSE, span = 0.5) +
  labs(title = "Weekly Unemployment Filings in Arkansas State",
       subtitle = "As of April 24th",
       x = "Date",
       y = "Case Count") +
  theme_classic()

ggplot(arkansas_covidata, aes(x = date, y = deriv_cases)) +
  geom_line() +
  geom_smooth(se = FALSE, span = 0.3) +
  labs(title = "Growth of Covid-19 Cases in Arkansas State",
       subtitle = "As of April 24th",
       x = "Date",
       y = "First Derivative of Case Count") +
  theme_classic()

ggplot(arkansas_covidata, aes(x = date, y = total_cases)) +
  geom_line() +
  labs(title = "Total Covid-19 Cases in Arkansas State",
       subtitle = "As of April 24th",
       x = "Date",
       y = "First Derivative of Case Count") +
  theme_classic()
  
```




```{r scatter-plot-unemployment-covid, echo=FALSE, fig.align='center'}

joined_data <- covidata_us %>%
  inner_join(unemployment_data_by_state, by = c("province_state", "date")) %>%
  filter(cases > 0) %>%
  group_by(province_state, date, week, initial_claims) %>%
  summarize(total_cases = sum(cases)) %>%
  mutate(log_total_cases = log(total_cases), log_initial_claims = log(initial_claims))

ggplot(joined_data, aes(x = total_cases, y = initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "Coronavirus Cases",
    y = "Weekly Unemployment Claims",
    color = "Month",
    title = "National Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across all 50 States, appears to show a strong positive correlation"
  )

ggplot(joined_data, aes(x = log_total_cases, y = log_initial_claims, color = date)) +
  geom_point() +
  geom_smooth(method = "loess") +
  theme_classic() +
  labs(
    x = "Natural Log of Coronavirus Cases",
    y = "Natural Log of Weekly Unemployment Claims",
    color = "Month",
    title = "National Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across all 50 States, appears to show a strong positive correlation"
  )
```

```{r scatter-plot-unemployment-covid-shutdown-early, echo=FALSE, fig.align='center'}

x1 <- covidata_us %>%
  filter(province_state %in% c("New York", "California", "Washington", "Oregon", "Illinois", "Louisiana", "Ohio", "New Jersey", "Connecticut"))

x2 <- unemployment_data_by_state %>%
  filter(province_state %in% c("New York", "California", "Washington", "Oregon", "Illinois", "Louisiana", "Ohio", "New Jersey", "Connecticut"))

joined_data3 <- x1 %>%
  inner_join(x2, by = c("province_state", "date")) %>%
  group_by(province_state, date, week, initial_claims) %>%
  summarize(total_cases = sum(cases)) %>%
  filter(total_cases > 0) %>%
  mutate(log_total_cases = log(total_cases), log_initial_claims = log(initial_claims))

ggplot(joined_data3, aes(x = total_cases, y = initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "Coronavirus Cases",
    y = "Weekly Unemployment Claims",
    color = "Month",
    title = "Early Shutdown Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across 9 States, appears to show a strong positive correlation"
  )

ggplot(joined_data3, aes(x = log_total_cases, y = log_initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "Natural Log of Coronavirus Cases",
    y = "Natural Log of Weekly Unemployment Claims",
    color = "Month",
    title = "Early Shutdown Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across 9 States, appears to show a strong positive correlation"
  )
```

```{r scatter-plot-unemployment-covid-shutdown-early, echo=FALSE, fig.align='center'}

x3 <- covidata_us %>%
  filter(province_state %in% c("North Dakota", "South Dakota", "Nebraska", "Iowa", "Wyoming", "Utah", "Oklahoma", "Arkansas"))

x4 <- unemployment_data_by_state %>%
  filter(province_state %in% c("North Dakota", "South Dakota", "Nebraska", "Iowa", "Wyoming", "Utah", "Oklahoma", "Arkansas"))

joined_data4 <- x3 %>%
  inner_join(x4, by = c("province_state", "date")) %>%
  group_by(province_state, date, week, initial_claims) %>%
  summarize(total_cases = sum(cases)) %>%
  filter(total_cases > 0) %>%
  mutate(log_total_cases = log(total_cases), log_initial_claims = log(initial_claims))

ggplot(joined_data4, aes(x = total_cases, y = initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "Coronavirus Cases",
    y = "Weekly Unemployment Claims",
    color = "Month",
    title = "No Shutdown Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across 8 States, does not appear to show correlation"
  )

ggplot(joined_data4, aes(x = log_total_cases, y = log_initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "Natural Log of Coronavirus Cases",
    y = "Natural Log of Weekly Unemployment Claims",
    color = "Month",
    title = "No Shutdown Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across 8 States, does not appear to show correlation"
  )
```

```{r correlating-data, echo=FALSE, fig.align='center'}
# First, completing the correlation summary

joined_data4 %>%
  filter(date > "2020-03-01") %>%
  group_by(date) %>%
  summarise(correlation = cor(total_cases, initial_claims)) %>%
  gt() %>%
  tab_header(
    title = "Coronavirus Case Count on Weekly Unemployment Claims",
    subtitle = "Arranged by Date"
  ) %>%
  cols_label(
    date = "Date",
    correlation = "Correlation Coefficient"
  )

joined_data3 %>%
  filter(date > "2020-02-28") %>%
  group_by(date) %>%
  summarise(correlation = cor(total_cases, initial_claims)) %>%
  gt() %>%
  tab_header(
    title = "Coronavirus Case Count on Weekly Unemployment Claims",
    subtitle = "Arranged by Date"
  ) %>%
  cols_label(
    date = "Date",
    correlation = "Correlation Coefficient"
  )
```

```{r correlating-data, echo=FALSE, fig.align='center'}
# First, completing the correlation summary

joined_data %>%
  filter(date > "2020-03-01") %>%
  group_by(date) %>%
  summarise(correlation = cor(total_cases, initial_claims)) %>%
  gt() %>%
  tab_header(
    title = "Coronavirus Case Count on Weekly Unemployment Claims",
    subtitle = "Arranged by Date"
  ) %>%
  cols_label(
    date = "Date",
    correlation = "Correlation Coefficient"
  )
```

```{r scatter-plot-2, echo=FALSE, fig.align='center'}

joined_data2 <- covidata_us %>%
  inner_join(unemployment_data_by_state, by = c("province_state", "date")) %>%
  filter(cases > 0) %>%
  group_by(province_state, date, week, initial_claims) %>%
  summarize(total_cases = sum(cases)) %>%
  mutate(log_total_cases = log(total_cases), log_initial_claims = log(initial_claims))

joined_data2$deriv_cases = c(diff(joined_data2$total_cases) / diff(joined_data2$week), NA)

joined_data2 <- joined_data2 %>%
  mutate(log_deriv_cases = log(deriv_cases))

ggplot(joined_data2, aes(x = deriv_cases, y = initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "First Derivative of Coronavirus Cases (Effective Growth Rate)",
    y = "Weekly Unemployment Claims",
    color = "Month",
    title = "National Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across all 50 States, appears to show a strong positive correlation"
  )

ggplot(joined_data2, aes(x = log_deriv_cases, y = log_initial_claims, color = date)) +
  geom_point() +
  theme_classic() +
  labs(
    x = "Natural Log of First Derivative of Coronavirus Cases (Effective Growth Rate)",
    y = "Natural Log Weekly Unemployment Claims",
    color = "Month",
    title = "National Unemployment Claims per Week versus Total Coronavirus Cases",
    subtitle = "Grouped across all 50 States, appears to show a strong positive correlation"
  )
```

```{r correlating-data-2, echo=FALSE, fig.align='center'}
# First, completing the correlation summary

joined_data2 %>%
  filter(date > "2020-03-01" & date != "2020-04-18") %>%
  group_by(date) %>%
  summarise(correlation = cor(log_deriv_cases, log_initial_claims)) %>%
  gt() %>%
  tab_header(
    title = "Coronavirus Growth Rate on Weekly Unemployment Claims",
    subtitle = "Arranged by Date"
  ) %>%
  cols_label(
    date = "Date",
    correlation = "Correlation Coefficient"
  )

joined_data2 %>%
  filter(date > "2020-03-01" & date != "2020-04-18") %>%
  group_by(date) %>%
  summarise(correlation = cor(log_deriv_cases, log_initial_claims)) %>%
  summarise(average = mean(correlation))
```


```{r saving-rds-files, echo=FALSE}
# Saving all my previous objects into RDS files that I will use in the shiny app

saveRDS(new_york_unemployment, file = "shiny-app/rdsObjects/new_york_unemployment.rds")
saveRDS(new_york_covidata, file = "shiny-app/rdsObjects/new_york_covidata.rds")
saveRDS(national_unemployment, file = "shiny-app/rdsObjects/national_unemployment.rds")
saveRDS(covidata_us_total, file = "shiny-app/rdsObjects/covidata_us_total.rds")
saveRDS(joined_data, file = "shiny-app/rdsObjects/joined_data.rds")
saveRDS(joined_data2, file = "shiny-app/rdsObjects/joined_data2.rds")


```



$~$

### Shiny App Link

https://michaeldwu.shinyapps.io/finalproject_shiny/

$~$
